/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvc_CvcHelper */

#ifndef _Included_cvc_CvcHelper
#define _Included_cvc_CvcHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1init
  (JNIEnv *, jclass);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_deinit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1deinit
  (JNIEnv *, jclass);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_calibratorInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1calibratorInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_calibratorCollectImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1calibratorCollectImage
  (JNIEnv *, jclass);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_calibratorStereoCalibrate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1calibratorStereoCalibrate
  (JNIEnv *, jclass);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_detectFace
 * Signature: (ILcvc/CvcRect;[I[I)I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1detectFace
  (JNIEnv *, jclass, jint, jobject, jintArray, jintArray);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_setLivingFaceThreshold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1setLivingFaceThreshold
  (JNIEnv *, jclass, jint);

/*
 * Class:     cvc_CvcHelper
 * Method:    CVC_determineLivingFace
 * Signature: ([I[B[I)I
 */
JNIEXPORT jint JNICALL Java_cvc_CvcHelper_CVC_1determineLivingFace
  (JNIEnv *, jclass, jintArray, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
